language: node_js
node_js:
  - 12
  - node
services: postgresql
before_script: 
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm install
  - npm run test
notification:
  - email: false
after_success:
  - npm run coverage